name: 'Package Linux Binaries'
description: 'Package Linux Binaries'
inputs:
  system:
    description: 'Package system [deb,rpm]'
    required: true
  tested_image:
    description: 'Tested docker image'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Download wazuh agent package
      uses: actions/download-artifact@v4
      with:
        pattern: '*.${{ inputs.system }}'

    - name: Prepare package
      run: |
        cp wazuh-agent*/wazuh-agent* /tmp
      shell: bash

    - name: Test DEB package installation
      uses: ./.github/actions/test-install-components
      with:
        system: ${{ inputs.system }}
        tested_docker: ${{ inputs.tested_image }}
