name: 'Test install Wazuh agent package'
description: 'Test install Wazuh agent package'
inputs:
  system:
    description: 'Package system [DEB, RPM]'
    required: true
  architecture:
    description: 'Package architecture'
    required: true
  tested_docker:
    description: 'image:tag of tested Docker'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Run test install Wazuh agent package
      shell: bash
      run: |
        sudo docker run \
          -v $GITHUB_WORKSPACE/.github/actions/test-install-components/:/tests \
          -v /tmp/:/packages \
          --entrypoint '/tests/install_component.sh' \
          ${{ inputs.architecture == 'arm64' && 'arm64v8' || 'amd64' }}/${{ inputs.tested_docker }}
        
    - name: Check test result
      shell: bash
      run: |    
        if grep -iq "wazuh-agent*" /tmp/status.log ; then
          echo "Installation successfully."
        else
          echo "The installation could not be completed";
          exit 1;
        fi
